Neos:
  Flow:
    i18n:
      defaultLocale: de
    resource:
      targets:
        localWebDirectoryPersistentResourcesTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemSymlinkTarget'
          targetOptions:
            relativeSymlinks: true
        localWebDirectoryStaticResourcesTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemSymlinkTarget'
          targetOptions:
            relativeSymlinks: true
  Media:
    thumbnailPresets:
      'Js.FamilyHelp:presetLg':
        maximumWidth: 1200
        maximumHeight: 800
      'Js.FamilyHelp:presetSm':
        maximumWidth: 940
        maximumHeight: 627
      'Js.FamilyHelp:presetXs':
        maximumWidth: 720
        maximumHeight: 480
      'Js.FamilyHelp:presetXxs':
        maximumWidth: 450
        maximumHeight: 300
#  Form:
#    yamlPersistenceManager:
#      savePath: 'resource://Js.FamilyHelp/Private/Form/'
